language: python
python:
  - 3.8
  - 3.7
  - 3.6
install: pip install -U tox-travis
script: tox
deploy:
  skip_cleanup: true
  ski_existing: true
  provider: pypi
  distributions: sdist bdist_wheel
  user: "__token__"
  password: pypi-AgEIcHlwaS5vcmcCJDNkMmI4MjNkLTRkNDUtNDc4ZS05Mzk2LTk3ZjUyNjM4ODA4MwACJXsicGVybWlzc2lvbnMiOiAidXNlciIsICJ2ZXJzaW9uIjogMX0AAAYgvAHUnkDRRgimTKf7Zr7ylAvsSIYRCQcXJ0RNzehwxRk
  on:
    tags: true
    repo: fabiofumarola/polimorfo
